[versions]
agp = "8.5.1"
ccp = "2.5.1"
glide = "4.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
libphonenumber = "8.13.0"
libphonenumberVersion = "8.12.10"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
okhttp = "4.11.0"
preference = "1.2.1"

[libraries]
ccp = { module = "com.hbb20:ccp", version.ref = "ccp" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
googlecode-libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumberVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
libphonenumber-v8130 = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

